In [1]:
import pickle
import numpy as np

In [3]:
ohe_s = pickle.load(open('models/ohe_s.pkl','rb'))
ohe_e = pickle.load(open('models/ohe_e.pkl','rb'))
dc = pickle.load(open('models/dc.pkl','rb'))

In [4]:
test_i = np.array([2,'male',56.0,1,0,10,'S'],dtype=object).reshape(1,7)

In [5]:
testis = ohe_s.transform(test_i[:,1].reshape(1,1))

z:\machineln\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [6]:
testis

array([[0., 1.]])

In [7]:
testie = ohe_e.transform(test_i[:,-1].reshape(1,1))

In [8]:
testie

array([[0., 0., 1.]])

In [9]:
testia = test_i[:,2].reshape(1,1)

In [10]:
testia

array([[56.0]], dtype=object)

In [12]:
test_i_t = np.concatenate((test_i[:,[0,3,4,5]],testis,testia,testie),axis=1)

In [13]:
test_i_t.shape

(1, 10)

In [14]:
dc.predict(test_i_t)

array([0])