# Array Attributes

In [3]:
import numpy as np

In [4]:
array = np.array([[1,2,3],[4,5,6]])
print(array.shape)

(2, 3)


In [6]:
array.flatten()

array([1, 2, 3, 4, 5, 6])

In [8]:
arrays = np.arange(1,13).reshape(4,3)
print(arrays)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Datatypes


In [9]:
np.array([1.35,1.4,34.5]).dtype

dtype('float64')

In [10]:
np.array(['I','am','learning','numpy']).dtype

dtype('<U8')

In [11]:
np.array([1,2,3,4]).dtype

dtype('int64')

# Datatypes as argument

In [15]:
float32=np.array([1.32,5.78,1.33],dtype=np.float32)
float32.dtype

dtype('float32')

# Type Conversion


In [17]:
boolean_array = np.array([True,False,True,False],dtype=np.bool_)
boolean_array.astype(np.int64)

array([1, 0, 1, 0])

In [18]:
float_array = np.array([2.33,2.66,5.22,2.33],dtype=np.float32)
float_array.astype(np.int64)

array([2, 2, 5, 2])

# Indexing,iteration and slicing

In [31]:
a = np.array([1,2,3,5])
print(a[0])

1


In [33]:
print(a[-1])

5


In [27]:
array_2D = np.arange(1,13).reshape(3,4)
print(array_2D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Row index


In [35]:
print(array_2D[0])

[1 2 3 4]


#### Column index

In [38]:
print(array_2D[:,1])

[ 2  6 10]


### slicing


In [40]:
print(a[2:4])

[3 5]


In [43]:
print(array_2D[1:3])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [44]:
print(array_2D[:,2:4])

[[ 3  4]
 [ 7  8]
 [11 12]]


In [47]:
new_array=np.arange(1,21).reshape(4,5)
print(new_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [48]:
print(new_array[1:3,2:4])

[[ 8  9]
 [13 14]]


In [49]:
for i in np.nditer(new_array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
