# Numpy Operations


In [1]:
import numpy as np

In [8]:
arr1= np.array([1,2,3,4,5,6])
arr2 = np.array([5,6,7,8,9,2])

In [9]:
arr1-arr2

array([-4, -4, -4, -4, -4,  4])

In [10]:
arr1*arr2

array([ 5, 12, 21, 32, 45, 12])

In [11]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [13]:
arr1>3

array([False, False, False,  True,  True,  True])

In [19]:
arr4 = np.arange(1,13).reshape(4,3)
arr5 = np.arange(10,22).reshape(3,4)

In [20]:
arr4.dot(arr5)

array([[ 92,  98, 104, 110],
       [218, 233, 248, 263],
       [344, 368, 392, 416],
       [470, 503, 536, 569]])

In [23]:
print(arr5.max())

21


In [24]:
print(arr5.min())

10


In [28]:
arr7 = np.arange(6).reshape(2,3)
print(arr7)

[[0 1 2]
 [3 4 5]]


### Check the minimum value column-wise

In [29]:
print(arr7.min(axis=0))

[0 1 2]


### Check the minimum value row-wise

In [30]:
print(arr7.min(axis=1))

[0 3]


In [31]:
print(arr7.sum())

15


In [32]:
print(arr7.sum(axis=0))

[3 5 7]


In [33]:
print(arr7.sum(axis=1))

[ 3 12]


In [34]:
print(arr7.mean())

2.5


In [35]:
print(arr7.std())

1.707825127659933


In [36]:
print(np.sin(arr7))

[[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]]


In [37]:
print(np.median(arr7))

2.5


In [38]:
print(np.exp(arr7))

[[  1.           2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003 148.4131591 ]]
