# Broadcasting

In [24]:
import numpy as np

In [25]:
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(6,12).reshape(2,3)

In [26]:
arr1 + arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [27]:
a1 = np.arange(3).reshape(1,3)
a2 = np.arange(6).reshape(2,3)

In [28]:
a1 + a2

array([[0, 2, 4],
       [3, 5, 7]])

In [29]:
a3 = np.arange(9).reshape(3,3)
a4 = np.arange(6).reshape(2,3)

In [30]:
a3 + a4

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [31]:
a5 = np.arange(3).reshape(1,3)
a6 = np.arange(16).reshape(4,4)

In [32]:
a5 + a6

ValueError: operands could not be broadcast together with shapes (1,3) (4,4) 

In [33]:
a7 = np.arange(3).reshape(1,3)
a8 = np.arange(3).reshape(3,1)

In [34]:
a7 + a8

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [35]:
a9 = np.arange(1).reshape(1,1)
a10 = np.arange(10).reshape(5,2)
print(a9)
print(a10)

[[0]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [36]:
a9 + a10

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [37]:
a11 = np.arange(4)
print(a11)
a12 = np.arange(12).reshape(3,4)
print(a12)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
a11 + a12

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [39]:
a13 = np.arange(2).reshape(1,2)
a14 = np.arange(16).reshape(4,4)
a13 + a14

ValueError: operands could not be broadcast together with shapes (1,2) (4,4) 

# Sorting

In [40]:
a = np.random.randint(1,100,15)
a

array([37, 16, 10,  5, 81, 12, 38, 49, 11, 85, 23, 48,  7,  1, 34],
      dtype=int32)

In [41]:
np.sort(a)

array([ 1,  5,  7, 10, 11, 12, 16, 23, 34, 37, 38, 48, 49, 81, 85],
      dtype=int32)

In [42]:
b = np.random.randint(1,100,24).reshape(6,4)
b


array([[ 2, 86, 63, 28],
       [75, 63, 84, 83],
       [24, 62, 12, 24],
       [91, 59, 94, 59],
       [ 6, 99,  9, 80],
       [16, 57, 93, 62]], dtype=int32)

In [43]:
np.sort(b,axis=0)

array([[ 2, 57,  9, 24],
       [ 6, 59, 12, 28],
       [16, 62, 63, 59],
       [24, 63, 84, 62],
       [75, 86, 93, 80],
       [91, 99, 94, 83]], dtype=int32)

### Sorting The Array In Descending Order

In [44]:
np.sort(a)[::-1]

array([85, 81, 49, 48, 38, 37, 34, 23, 16, 12, 11, 10,  7,  5,  1],
      dtype=int32)

# Concatenation

In [45]:
b1 = np.arange(6).reshape(2,3)
b2 = np.arange(6,12).reshape(2,3)

print(b1)
print(b2)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [46]:
np.concatenate((b1,b2),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
np.concatenate((b1,b2),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.where()

In [48]:
a

array([37, 16, 10,  5, 81, 12, 38, 49, 11, 85, 23, 48,  7,  1, 34],
      dtype=int32)

In [49]:
# find all indices with value greater than 50
np.where(a>50)

(array([4, 9]),)

In [50]:
# np.where(condition,true,false)
np.where(b>50,0,b)

array([[ 2,  0,  0, 28],
       [ 0,  0,  0,  0],
       [24,  0, 12, 24],
       [ 0,  0,  0,  0],
       [ 6,  0,  9,  0],
       [16,  0,  0,  0]], dtype=int32)

# np.cumsum()

In [51]:
a

array([37, 16, 10,  5, 81, 12, 38, 49, 11, 85, 23, 48,  7,  1, 34],
      dtype=int32)

In [52]:
np.cumsum(a)

array([ 37,  53,  63,  68, 149, 161, 199, 248, 259, 344, 367, 415, 422,
       423, 457])

In [53]:
b


array([[ 2, 86, 63, 28],
       [75, 63, 84, 83],
       [24, 62, 12, 24],
       [91, 59, 94, 59],
       [ 6, 99,  9, 80],
       [16, 57, 93, 62]], dtype=int32)

In [54]:
np.cumsum(b,axis=0)

array([[  2,  86,  63,  28],
       [ 77, 149, 147, 111],
       [101, 211, 159, 135],
       [192, 270, 253, 194],
       [198, 369, 262, 274],
       [214, 426, 355, 336]])

In [55]:
np.cumsum(b,axis=1)

array([[  2,  88, 151, 179],
       [ 75, 138, 222, 305],
       [ 24,  86,  98, 122],
       [ 91, 150, 244, 303],
       [  6, 105, 114, 194],
       [ 16,  73, 166, 228]])

In [56]:
np.cumprod(a)

array([                  37,                  592,                 5920,
                      29600,              2397600,             28771200,
                 1093305600,          53571974400,         589291718400,
             50089796064000,     1152065309472000,    55299134854656000,
         387093943982592000,   387093943982592000, -5285549978301423616])

In [57]:
np.cumprod(b,axis=0)

array([[           2,           86,           63,           28],
       [         150,         5418,         5292,         2324],
       [        3600,       335916,        63504,        55776],
       [      327600,     19819044,      5969376,      3290784],
       [     1965600,   1962085356,     53724384,    263262720],
       [    31449600, 111838865292,   4996367712,  16322288640]])

# np.histogram()

##### It represents the number of frequecy of data distribution

In [60]:
a

array([37, 16, 10,  5, 81, 12, 38, 49, 11, 85, 23, 48,  7,  1, 34],
      dtype=int32)

In [61]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90])

(array([3, 4, 1, 3, 2, 0, 0, 0, 2]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

# np.flip()

In [62]:
np.flip(a)

array([34,  1,  7, 48, 23, 85, 11, 49, 38, 12, 81,  5, 10, 16, 37],
      dtype=int32)

In [63]:
b

array([[ 2, 86, 63, 28],
       [75, 63, 84, 83],
       [24, 62, 12, 24],
       [91, 59, 94, 59],
       [ 6, 99,  9, 80],
       [16, 57, 93, 62]], dtype=int32)

In [64]:
np.flip(b)

array([[62, 93, 57, 16],
       [80,  9, 99,  6],
       [59, 94, 59, 91],
       [24, 12, 62, 24],
       [83, 84, 63, 75],
       [28, 63, 86,  2]], dtype=int32)

In [65]:
np.flip(b,axis=0)

array([[16, 57, 93, 62],
       [ 6, 99,  9, 80],
       [91, 59, 94, 59],
       [24, 62, 12, 24],
       [75, 63, 84, 83],
       [ 2, 86, 63, 28]], dtype=int32)

In [67]:
b

array([[ 2, 86, 63, 28],
       [75, 63, 84, 83],
       [24, 62, 12, 24],
       [91, 59, 94, 59],
       [ 6, 99,  9, 80],
       [16, 57, 93, 62]], dtype=int32)

In [66]:
np.flip(b,axis=1)

array([[28, 63, 86,  2],
       [83, 84, 63, 75],
       [24, 12, 62, 24],
       [59, 94, 59, 91],
       [80,  9, 99,  6],
       [62, 93, 57, 16]], dtype=int32)

# np.delete()

In [68]:
a

array([37, 16, 10,  5, 81, 12, 38, 49, 11, 85, 23, 48,  7,  1, 34],
      dtype=int32)

In [69]:
np.delete(a,2)

array([37, 16,  5, 81, 12, 38, 49, 11, 85, 23, 48,  7,  1, 34],
      dtype=int32)

In [71]:
np.delete(a,[0,2,4,6])

array([16,  5, 12, 49, 11, 85, 23, 48,  7,  1, 34], dtype=int32)